"""
Report — pure Python email builder + Gmail MCP call via mcp_client.
build_report_email() is deterministic, no LLM tokens consumed.
create_report_agent() kept for ADK CLI / agents.json backwards compat.
"""

import os

from google.adk.agents import LlmAgent

from .model_config import get_primary_model


def build_report_email(student_name: str, analytics: dict) -> tuple[str, str]:
    """
    Build plain-text email subject + body for teacher.
    Returns (subject, body). No LLM calls.
    """
    first_name = student_name.split()[0] if student_name else "Student"
    scores = analytics.get("scores", {})
    total = analytics.get("total_score", 0)
    max_p = analytics.get("max_possible", 20)
    pct = analytics.get("percentage", 0)

    strengths_text = "\n".join(f"  - {s}" for s in analytics.get("key_strengths", []))
    weaknesses_text = "\n".join(f"  - {w}" for w in analytics.get("key_weaknesses", []))
    suggestions_text = "\n".join(
        f"  {i+1}. {s}" for i, s in enumerate(analytics.get("improvement_suggestions", []))
    )

    subject = f"CritiqAI Session Report — {first_name}"
    body = f"""Dear Teacher,

Here is the critical thinking session report for {first_name}.

OVERALL SCORE: {total}/{max_p} ({pct}%)

DIMENSION SCORES:
  - Logical Coherence: {scores.get('logical_coherence', 0)}/5
  - Evidence Quality: {scores.get('evidence_quality', 0)}/5
  - Counterargument Handling: {scores.get('counterargument_handling', 0)}/5
  - Scope Awareness: {scores.get('scope_awareness', 0)}/5

STRENGTHS:
{strengths_text if strengths_text else '  (none at 4-5 level this session)'}

AREAS TO FOCUS ON:
{weaknesses_text if weaknesses_text else '  (no critical weaknesses this session)'}

SUGGESTIONS FOR NEXT SESSION:
{suggestions_text}

This report was generated by CritiqAI. Please review before sharing with the student.

CritiqAI System"""

    return subject, body


# Kept for ADK CLI / agents.json backwards compat
REPORT_PROMPT = """You are an academic reporting agent. Use the create_draft Gmail MCP tool to create a plain-text email draft for the teacher. NEVER call send_email."""


def create_report_agent() -> LlmAgent:
    return LlmAgent(
        name="report",
        model=get_primary_model(),
        instruction=REPORT_PROMPT,
        output_key="report_draft_id",
    )
